name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # main 브랜치에 코드가 올라올 때마다 실행
  workflow_dispatch: # 수동으로 실행하고 싶을 때 버튼 생성

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: actions/deploy-pages@v4
